### ISSUE TITLE
Laravel 4.2 Incorrect Datetime format

### ISSUE THREAD

**Issue by kartikpanchal** [davelip/laravel-database-queue#11]
Hi guy

I have develop new application in laravel 4.2. I update davelip package via composer. I set up all thing as per github instruction. But some how get error like:

[Illuminate\Database\QueryException]
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2
015-09-25T18:56:51+0000' for column 'timestamp' at row 1 (SQL: update `queues` set `status` = 1, `retries` = 1, `timestamp` = 2015-09-25T18:56:51+0000
, `updated_at` = 2015-09-25 18:56:51 where `id` = 14)

I was create queue table from php artisan migrate command but when ever I used queue for bulk mail sending I got same error in queue:listen command.

I needfull help regarding this Issue.

**Comment by davelip** [comment]
Hi @kartikpanchal

   I can't reproduce your error.

Could you send me your configuration of laravel environment?
- davelip/laravel-database-queue package version
- app/config/queue.php (or equivalent local environment configuration)
- DBMS used (type and version)

In 0.5.3 package I have tried to change the way I set timestamp for a failed job.
Check if this fix your issue.

I apologize for my delay in this response.

**Comment by kartikpanchal** [comment]
Hi davelip 

I was sort it out. 

But I need one more help.

How can I run '$php artisan queue:listen' command in shared hosting.
I am using hostgator hosting provider. And what should be my directory structure. Please let me guide in detail as soon as possible

**Comment by davelip** [comment]
Hi @kartikpanchal 

   i don't know hostgator hosting provider.

Do you have an ssh access to the environment? 
If yes access via ssh and from your command line type:

```
php artisan queue:listen
```

If not: you can use http://laravel-tricks.com/tricks/run-artisan-commands-form-route-or-controller anche call your controller via an http call (...or change hosting solution :)).

Bye!
