### ISSUE TITLE
Question about default queue and job priority

### ISSUE THREAD

**Issue by driade** [davelip/laravel-database-queue#16]
Hello, good night.

It seems that setting the default queue to null produces that any job with an specified queue name, such as "high", would never be processed. 

Maybe I'm wrong but I think that if the default queue is not specified every job should be processed, with the id as the sorting key. This is addressed at DatabaseQueue.php, line 156.

Thanks!

**Comment by driade** [comment]
I'm going to close the issue, I've checked Laravel's source code in the current version and it seems that it works the same way.

Sorry for the mistake!

**Comment by davelip** [comment]
Hi @driade the behaviour You speak about had seemed strange also to me.
But Laravel's queue, in that version, works in that way.

Thanks for your partecipation.

Bye
