### ISSUE TITLE
Question about `status` field in queues table

### ISSUE THREAD

**Issue by atefBB** [davelip/laravel-database-queue#18]
Hi. 
What is the role of `status` column in the `queues` table?!
I don't understand this sentence `Concurrency are managed by status column in the queues table` in the doc. Help PLZ!

**Comment by mferrara** [comment]
0 = job has yet to be processed
1 = job was attempted and failed? (not positive on this)
2 = job is in process

> I don't understand this sentence Concurrency are managed by status column in the queues table in the doc. 

My impression there is that the same job won't be picked up by multiple workers due to checking the status column on the jobs.

**Comment by atefBB** [comment]
Thx. What about The 3 status code?

**Comment by atefBB** [comment]
@davelip help !

**Comment by davelip** [comment]
Statuses are referenced here: 
https://github.com/davelip/laravel-database-queue/blob/master/src/Models/Job.php


The Job selection are explained in: https://github.com/davelip/laravel-database-queue/blob/master/src/DatabaseQueue.php
- storeJob() method create a Job in status OPEN
- pop() method select Job in status OPEN or WAITING and put them in status STARTED ("Concurrency are managed by status column in the queues table")


The Job execution class (see https://laravel.com/docs/4.2/queues): https://github.com/davelip/laravel-database-queue/blob/master/src/Jobs/DatabaseJob.php
- release() method put Job in WAITING status
- fire() method put Job in FINISHED status if completed (not deleted and not released)


For failed job: every job run upgrade the tries number for every job (see https://laravel.com/docs/4.2/queues#failed-jobs)


For locking: https://laravel.com/docs/4.2/queries#pessimistic-locking and https://github.com/davelip/laravel-database-queue/blob/master/src/DatabaseQueue.php

Available for further clarification

**Comment by atefBB** [comment]
https://github.com/davelip/laravel-database-queue/blob/master/src/Models/Job.php#L22 helps!
Thank you.

**Comment by davelip** [comment]
:+1:
